version: '3'
services:
  ranger:
    build:
      context: .
      dockerfile: Dockerfile.ranger
      args:
        - RANGER_VERSION=${RANGER_VERSION}
        - RANGER_DB_TYPE=postgres
        - RANGER_ADMIN_JAVA_VERSION=${RANGER_ADMIN_JAVA_VERSION}
    image: ranger:latest
    volumes:
      - ./krb5.conf:/etc/krb5.conf
      - /etc/security/keytabs/rangeradmin.keytab:/etc/security/keytabs/rangeradmin.keytab
      - /etc/security/keytabs/http_keytab.keytab:/etc/security/keytabs/http_keytab.keytab
      - ./install.properties:/opt/ranger/ranger-3.0.0-SNAPSHOT-admin/install.properties
      - ./hosts:/etc/hosts
      - ./resolv.conf:/etc/resolv.conf
    container_name: ranger
    hostname: ranger.example.com
    stdin_open: true
    tty: true
    network_mode: host
    ports:
      - "6080:6080"
    depends_on:
      ranger-db:
        condition: service_healthy
    environment:
      - RANGER_VERSION
      - RANGER_DB_TYPE
      - DEBUG_ADMIN=${DEBUG_ADMIN:-false}
    command: ["/bin/bash", "-c", "while true; do echo 'Container is running...'; done"]
